[package]
name = "predictiv"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-files = "0.6.9"
actix-multipart = "0.7.2"
actix-web = "4.12.1"
image = "0.25.9"
serde = "1.0.228"
